include: ./analysis_options_shared.yaml

analyzer:
  exclude:
    - _docs/**
    - packages/rust/target/**
    - packages/exptlorer/build/**
  enable-experiment:
    - primary-constructors

plugins:
  riverpod_lint: ^3.1.0
