// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'disk.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `disks_info`

Future<List<DiskInfo>> disks() => RustLib.instance.api.crateApiDiskDisks();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DiskInfo>>
abstract class DiskInfo implements RustOpaqueInterface {
  /// Returns the available disk size, in bytes.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {}B", disk.name(), disk.available_space());
  /// }
  /// ```
  Future<BigInt> availableSpace();

  /// Returns the file system used on this disk (so for example: `EXT4`, `NTFS`, etc...).
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {:?}", disk.name(), disk.file_system());
  /// }
  /// ```
  Future<String> fileSystem();

  /// Returns `true` if the disk is read-only.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] is read-only: {}", disk.name(), disk.is_read_only());
  /// }
  /// ```
  Future<bool> isReadOnly();

  /// Returns `true` if the disk is removable.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {}", disk.name(), disk.is_removable());
  /// }
  /// ```
  Future<bool> isRemovable();

  /// Returns the kind of disk.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {:?}", disk.name(), disk.kind());
  /// }
  /// ```
  Future<DiskKind> kind();

  /// Returns the mount point of the disk (`/` for example).
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {:?}", disk.name(), disk.mount_point());
  /// }
  /// ```
  Future<String> mountPoint();

  /// Returns the disk name.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("{:?}", disk.name());
  /// }
  /// ```
  Future<String> name();

  /// Updates the disk' information with everything loaded.
  ///
  /// Equivalent to <code>[Disk::refresh_specifics]\([DiskRefreshKind::everything]\())</code>.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let mut disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list_mut() {
  ///     disk.refresh();
  /// }
  /// ```
  Future<bool> refresh();

  /// Updates the disk's information corresponding to the given [`DiskRefreshKind`].
  ///
  /// ```no_run
  /// use sysinfo::{Disks, DiskRefreshKind};
  ///
  /// let mut disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list_mut() {
  ///     disk.refresh_specifics(DiskRefreshKind::nothing());
  /// }
  /// ```
  Future<bool> refreshSpecifics({required DiskRefreshKind refreshes});

  /// Returns the total disk size, in bytes.
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] {}B", disk.name(), disk.total_space());
  /// }
  /// ```
  Future<BigInt> totalSpace();

  /// Returns number of bytes read and written by the disk
  ///
  /// ```no_run
  /// use sysinfo::Disks;
  ///
  /// let disks = Disks::new_with_refreshed_list();
  /// for disk in disks.list() {
  ///     println!("[{:?}] disk usage: {:?}", disk.name(), disk.usage());
  /// }
  /// ```
  Future<DiskUsage> usage();
}

@freezed
sealed class DiskKind with _$DiskKind {
  const DiskKind._();

  const factory DiskKind.hdd() = DiskKind_HDD;
  const factory DiskKind.ssd() = DiskKind_SSD;
  const factory DiskKind.unknown(PlatformInt64 field0) = DiskKind_Unknown;
}

/// Used to determine what you want to refresh specifically on the [`Disk`] type.
///
/// * `kind` is about refreshing the [`Disk::kind`] information.
/// * `storage` is about refreshing the [`Disk::available_space`] and [`Disk::total_space`] information.
/// * `io_usage` is about refreshing the [`Disk::usage`] information.
///
/// ```no_run
/// use sysinfo::{Disks, DiskRefreshKind};
///
/// let mut disks = Disks::new_with_refreshed_list_specifics(DiskRefreshKind::everything());
///
/// for disk in disks.list() {
///     assert!(disk.total_space() != 0);
/// }
/// ```
class DiskRefreshKind {
  final bool kind;
  final bool storage;
  final bool ioUsage;

  const DiskRefreshKind({
    required this.kind,
    required this.storage,
    required this.ioUsage,
  });

  static Future<DiskRefreshKind> everything() =>
      RustLib.instance.api.crateApiDiskDiskRefreshKindEverything();

  @override
  int get hashCode => kind.hashCode ^ storage.hashCode ^ ioUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskRefreshKind &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          storage == other.storage &&
          ioUsage == other.ioUsage;
}

class DiskUsage {
  final BigInt totalWrittenBytes;
  final BigInt writtenBytes;
  final BigInt totalReadBytes;
  final BigInt readBytes;

  const DiskUsage({
    required this.totalWrittenBytes,
    required this.writtenBytes,
    required this.totalReadBytes,
    required this.readBytes,
  });

  @override
  int get hashCode =>
      totalWrittenBytes.hashCode ^
      writtenBytes.hashCode ^
      totalReadBytes.hashCode ^
      readBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskUsage &&
          runtimeType == other.runtimeType &&
          totalWrittenBytes == other.totalWrittenBytes &&
          writtenBytes == other.writtenBytes &&
          totalReadBytes == other.totalReadBytes &&
          readBytes == other.readBytes;
}
