// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_file_icon_rgba_full`, `icon_to_rgba`

Future<IconData?> getIconRgba({required String path, IconSize? size}) =>
    RustLib.instance.api.crateApiFileIconGetIconRgba(path: path, size: size);

class IconData {
  final int width;
  final int height;
  final Uint8List bgraBytes;

  const IconData({
    required this.width,
    required this.height,
    required this.bgraBytes,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ bgraBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bgraBytes == other.bgraBytes;
}

enum IconSize { large, small }
